### ISSUE TITLE
lightbox not in foreground

### ISSUE THREAD

**Issue by marscom65** [bpextensions/bpgallery#54]
here: https://kreatief.marscom.ch/index.php/wohnen/betreutes-wohnen-kreatief when clicking the thumbs, the large image is behind the menu bar. I tried all to force the z-index of the mfp-gallery to be like 999999999999 or whatever. No chance. Where can I change the z-index?
Thanks in advance
Martin

**Comment by artur-stepien** [comment]
You should not change the lightbox z-index. Instead, you should fix the menu z-index. 9999999999 is way to high. In short it forces menu above ALL of the content. Also, on some browsers it can be the highest z-index available to you will not be able to set anything above that. You should keep it not higher then 100-500 depending on the way the site is build.

**Comment by marscom65** [comment]
Thanks, Artur! I’ll get in touch with the dev of the menu.

 

Cheers


Martin

 

-- 

 

marscom 

Martin Scheidegger

Leimenstrasse 62 

CH-2575 Täuffelen

T +41 32 365 66 77

http://www.marscom.ch

 

 

Von: Artur Stępień ***@***.***>
Antworten an: bpextensions/bpgallery ***@***.***>
Datum: Freitag, 30. April 2021 um 10:35
An: bpextensions/bpgallery ***@***.***>
Cc: martin scheidegger ***@***.***>, Author ***@***.***>
Betreff: Re: [bpextensions/bpgallery] lightbox not in foreground (#54)

 

You should not change the lightbox z-index. Instead, you should fix the menu z-index. 9999999999 is way to high. In short it forces menu above ALL of the content. Also, on some browsers it can be the highest z-index available to you will not be able to set anything above that. You should keep it not higher then 100-500 depending on the way the site is build.

**Comment by artur-stepien** [comment]
> 
> Thanks, Artur! I’ll get in touch with the dev of the menu. Cheers Martin
> […](#)
> -- marscom Martin Scheidegger Leimenstrasse 62 CH-2575 Täuffelen T +41 32 365 66 77 http://www.marscom.ch Von: Artur Stępień ***@***.***> Antworten an: bpextensions/bpgallery ***@***.***> Datum: Freitag, 30. April 2021 um 10:35 An: bpextensions/bpgallery ***@***.***> Cc: martin scheidegger ***@***.***>, Author ***@***.***> Betreff: Re: [bpextensions/bpgallery] lightbox not in foreground (#54) You should not change the lightbox z-index. Instead, you should fix the menu z-index. 9999999999 is way to high. In short it forces menu above ALL of the content. Also, on some browsers it can be the highest z-index available to you will not be able to set anything above that. You should keep it not higher then 100-500 depending on the way the site is build. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

It is template related. Menu module itself has a z-index of 1000. Where top bar has 9999999999. So you should contact template developer or fix it yourself (what can be faster).
